# Generated by Django 5.1.6 on 2025-03-11 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooler', '0004_alter_task_tasker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='tasker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cooler.taskers'),
        ),
    ]
