# Generated by Django 5.1.6 on 2025-03-13 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooler', '0005_alter_task_tasker'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='created',
            new_name='create',
        ),
    ]
